title: HPC-EXCELERATE:- High Performance Computing, Genome Comparison, MPI, GECKO
description: 2-day HPC course of the ELIXIR-EXCELERATE project at University of Malaga
google_analytics: 
show_downloads: false
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
